version: '3'

volumes:
  dbdata:
    driver: local

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: digitalocean.com/php
    container_name: chat_app
    restart: unless-stopped
    tty: true
    depends_on:
      - web
      - db
      - mercure
    ports:
      - "8000:8000"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
       - ../:/var/www
       - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - db
      - web
      - mercure
      - redis
    networks:
      - chat

  #Nginx Service
  web:
    image: nginx:alpine
    container_name: chat_web
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "8043:443"
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - chat

  #Postgresql Service
  db:
    image: postgres:10.4-alpine
    container_name: chat_db
    volumes:
      - dbdata:/var/lib/postgresql/data
      - dbdata:/backups
    ports:
      - "5432:5432"
    env_file:
      - postgres/.env
    networks:
      - chat

  mercure:
    image: dunglas/mercure
    container_name: chat_mercure
    env_file:
      - mercure/.env
    ports:
      - "9090:80"

  redis:
    image: redis:3.2
    container_name: chat_redis
    networks:
      - chat

networks:
  chat:
